# Generated by Django 3.2.12 on 2024-03-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_comment_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
