# Generated by Django 3.2.12 on 2024-03-18 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_comment_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='discussion',
        ),
    ]
