# Generated by Django 5.0.2 on 2024-04-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_remove_comment_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
